[tool.poetry]
name = "phase_scrambled_corr"
version = "0.1.0"
description = "This module implements phase randomization surrogates and cross-correlation analysis following Ebisuzaki (1997)."
authors = ["Anthony Meza"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^2.3.1"
setuptools = "72.1.0"
wheel = "0.45.1"
matplotlib = "^3.10.3"
scipy = "^1.16.0"
statsmodels = "^0.14.5"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
