name: ci

on: [push, pull_request]

# grant the GITHUB_TOKEN permission to push pages
permissions:
  contents: write
  pages: write

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0            # get full history so gh-pages can detect changes
          persist-credentials: true # allow pushes with GITHUB_TOKEN

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies (including docs tools)
        run: poetry install --no-interaction

      - name: Install extra docs deps
        run: poetry run pip install sphinx sphinx-autoapi sphinx-rtd-theme

      - name: Test with pytest
        run: poetry run pytest PhaseScrambledCorrelations/tests/ --cov=PhaseScrambledCorrelations --cov-report=xml

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml

      - name: Build documentation
        run: cd docs/ && poetry run make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs/_build/html
